name: ZAP-Test

on:
  push:
    branches: [ master ]
permissions:
  issues: write
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # Thiết lập Python 3.11
      - name: Setup Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11.5
      
      # Cài đặt thư viện Python (requests, owasp zap)
      - name: Install python deps
        run: |
          python -m pip install --upgrade pip
          pip install requests python-owasp-zap-v2.4
      
      - name: Get working directory
        run: echo "$(pwd)"
      
      - name: Build Image
        run: docker build -t vulnerable-app .
      # SAST Scan
      - name: SAST Scan
        uses: AppThreat/sast-scan-action@master
        with:
          type: "python"
      - name: Upload SAST reports
        uses: actions/upload-artifact@v1
        with:
          name: reports
          path: reports
      # Chạy container trên cổng 5050
      - name: Run Docker Container
        run: |
          docker run -d -p 5050:5050 --name test-app vulnerable-app
          # Đợi một chút để container thật sự up
          sleep 10
          # Kiểm tra nhanh container
          curl -I http://localhost:5050 || exit 1
      

      # Chạy script test automation (e2e_zap.py) 
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://localhost:5050'
          cmd_options: '-a'
          http_login_form: '/login'
          http_login_http_username: 'admin'
          http_login_http_password: ${{ secrets.ZAP_USER_PW }}
          issue_title: 'ZAP Scan Report'